### ISSUE TITLE
Fix Package.json Missing Comma, Add "yeoman-generator" to keywords.

### ISSUE THREAD

**Issue by thomaswmanion** [Accenture/generator-mario#2]
Two Issues:
- Package.json is missing a comma.
- Add "yeoman-generator" as a keywords to the generator so Yeoman registers it as a generator that can be installed via `yo` => `Install a Generator`.

**Comment by Urnamma** [comment]
Thanks Tom, Slavo will fix it. Slavo also needs to add a picture on GitHub, and you need less Mustache ;)

**Comment by Urnamma** [comment]
Thanks for fixing, Tom! Appreciate it.

**Comment by thomaswmanion** [comment]
Mustache is great. No problem.
